import React from 'react';
import { Heart, Users, Award, BookOpen, Stethoscope, Shield } from 'lucide-react';
export function About() {
    return (React.createElement("div", { className: "min-h-screen bg-gray-50 py-12" },
        React.createElement("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" },
            React.createElement("div", { className: "text-center mb-16" },
                React.createElement("div", { className: "flex justify-center mb-6" },
                    React.createElement(Stethoscope, { className: "h-16 w-16 text-blue-600" })),
                React.createElement("h1", { className: "text-4xl font-bold text-gray-900 mb-6" }, "About MediBlog"),
                React.createElement("p", { className: "text-xl text-gray-600 max-w-3xl mx-auto" }, "Your trusted source for medical knowledge, health insights, and professional healthcare content. We bridge the gap between medical professionals and the public through accessible, accurate information.")),
            React.createElement("div", { className: "bg-white rounded-xl shadow-lg p-8 mb-12" },
                React.createElement("div", { className: "text-center mb-8" },
                    React.createElement("h2", { className: "text-3xl font-bold text-gray-900 mb-4" }, "Our Mission"),
                    React.createElement("p", { className: "text-lg text-gray-600 max-w-4xl mx-auto" }, "To democratize medical knowledge by providing accurate, peer-reviewed health information that empowers individuals to make informed decisions about their health and wellbeing.")),
                React.createElement("div", { className: "grid md:grid-cols-3 gap-8" },
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "bg-blue-100 rounded-full p-4 w-16 h-16 mx-auto mb-4 flex items-center justify-center" },
                            React.createElement(Heart, { className: "h-8 w-8 text-blue-600" })),
                        React.createElement("h3", { className: "text-xl font-semibold text-gray-900 mb-2" }, "Patient-Centered"),
                        React.createElement("p", { className: "text-gray-600" }, "Every article is written with the patient's understanding and wellbeing in mind.")),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "bg-green-100 rounded-full p-4 w-16 h-16 mx-auto mb-4 flex items-center justify-center" },
                            React.createElement(Shield, { className: "h-8 w-8 text-green-600" })),
                        React.createElement("h3", { className: "text-xl font-semibold text-gray-900 mb-2" }, "Evidence-Based"),
                        React.createElement("p", { className: "text-gray-600" }, "All content is backed by current medical research and peer-reviewed studies.")),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "bg-purple-100 rounded-full p-4 w-16 h-16 mx-auto mb-4 flex items-center justify-center" },
                            React.createElement(Users, { className: "h-8 w-8 text-purple-600" })),
                        React.createElement("h3", { className: "text-xl font-semibold text-gray-900 mb-2" }, "Community-Driven"),
                        React.createElement("p", { className: "text-gray-600" }, "Built by healthcare professionals for the global medical community.")))),
            React.createElement("div", { className: "bg-blue-600 text-white rounded-xl p-8 mb-12" },
                React.createElement("div", { className: "text-center mb-8" },
                    React.createElement("h2", { className: "text-3xl font-bold mb-4" }, "Our Impact"),
                    React.createElement("p", { className: "text-blue-100 text-lg" }, "Making a difference in healthcare education worldwide")),
                React.createElement("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-8" },
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "text-3xl font-bold mb-2" }, "500+"),
                        React.createElement("div", { className: "text-blue-200" }, "Published Articles")),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "text-3xl font-bold mb-2" }, "100+"),
                        React.createElement("div", { className: "text-blue-200" }, "Medical Writers")),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "text-3xl font-bold mb-2" }, "25+"),
                        React.createElement("div", { className: "text-blue-200" }, "Medical Specialties")),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "text-3xl font-bold mb-2" }, "1M+"),
                        React.createElement("div", { className: "text-blue-200" }, "Readers Reached")))),
            React.createElement("div", { className: "bg-white rounded-xl shadow-lg p-8 mb-12" },
                React.createElement("div", { className: "text-center mb-8" },
                    React.createElement("h2", { className: "text-3xl font-bold text-gray-900 mb-4" }, "Our Editorial Team"),
                    React.createElement("p", { className: "text-lg text-gray-600" }, "Led by experienced healthcare professionals and medical educators")),
                React.createElement("div", { className: "grid md:grid-cols-3 gap-8" },
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "bg-gray-200 rounded-full w-24 h-24 mx-auto mb-4 flex items-center justify-center" },
                            React.createElement(Users, { className: "h-12 w-12 text-gray-500" })),
                        React.createElement("h3", { className: "text-xl font-semibold text-gray-900 mb-2" }, "Dr. Sarah Johnson"),
                        React.createElement("p", { className: "text-blue-600 mb-2" }, "Chief Medical Editor"),
                        React.createElement("p", { className: "text-gray-600 text-sm" }, "Board-certified Internal Medicine physician with 15+ years of clinical experience")),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "bg-gray-200 rounded-full w-24 h-24 mx-auto mb-4 flex items-center justify-center" },
                            React.createElement(Users, { className: "h-12 w-12 text-gray-500" })),
                        React.createElement("h3", { className: "text-xl font-semibold text-gray-900 mb-2" }, "Dr. Michael Chen"),
                        React.createElement("p", { className: "text-blue-600 mb-2" }, "Senior Editor"),
                        React.createElement("p", { className: "text-gray-600 text-sm" }, "Cardiologist and medical researcher specializing in preventive medicine")),
                    React.createElement("div", { className: "text-center" },
                        React.createElement("div", { className: "bg-gray-200 rounded-full w-24 h-24 mx-auto mb-4 flex items-center justify-center" },
                            React.createElement(Users, { className: "h-12 w-12 text-gray-500" })),
                        React.createElement("h3", { className: "text-xl font-semibold text-gray-900 mb-2" }, "Dr. Emily Rodriguez"),
                        React.createElement("p", { className: "text-blue-600 mb-2" }, "Pediatric Editor"),
                        React.createElement("p", { className: "text-gray-600 text-sm" }, "Pediatrician and child health advocate with expertise in family medicine")))),
            React.createElement("div", { className: "bg-white rounded-xl shadow-lg p-8" },
                React.createElement("div", { className: "text-center mb-8" },
                    React.createElement("h2", { className: "text-3xl font-bold text-gray-900 mb-4" }, "Our Values")),
                React.createElement("div", { className: "grid md:grid-cols-2 gap-8" },
                    React.createElement("div", { className: "flex items-start space-x-4" },
                        React.createElement("div", { className: "bg-blue-100 rounded-lg p-3 flex-shrink-0" },
                            React.createElement(Award, { className: "h-6 w-6 text-blue-600" })),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Excellence"),
                            React.createElement("p", { className: "text-gray-600" }, "We maintain the highest standards in medical content creation and review processes."))),
                    React.createElement("div", { className: "flex items-start space-x-4" },
                        React.createElement("div", { className: "bg-green-100 rounded-lg p-3 flex-shrink-0" },
                            React.createElement(BookOpen, { className: "h-6 w-6 text-green-600" })),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Education"),
                            React.createElement("p", { className: "text-gray-600" }, "We believe in the power of education to improve health outcomes globally."))),
                    React.createElement("div", { className: "flex items-start space-x-4" },
                        React.createElement("div", { className: "bg-purple-100 rounded-lg p-3 flex-shrink-0" },
                            React.createElement(Shield, { className: "h-6 w-6 text-purple-600" })),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Integrity"),
                            React.createElement("p", { className: "text-gray-600" }, "We are committed to providing unbiased, accurate medical information."))),
                    React.createElement("div", { className: "flex items-start space-x-4" },
                        React.createElement("div", { className: "bg-yellow-100 rounded-lg p-3 flex-shrink-0" },
                            React.createElement(Heart, { className: "h-6 w-6 text-yellow-600" })),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Compassion"),
                            React.createElement("p", { className: "text-gray-600" }, "We approach every topic with empathy and understanding for patients and families."))))))));
}
