import React from 'react';
import { Shield, Eye, Lock, Users, FileText, AlertCircle } from 'lucide-react';
export function PrivacyPolicy() {
    return (React.createElement("div", { className: "min-h-screen bg-gray-50 py-12" },
        React.createElement("div", { className: "max-w-4xl mx-auto px-4 sm:px-6 lg:px-8" },
            React.createElement("div", { className: "bg-white rounded-xl shadow-lg p-8" },
                React.createElement("div", { className: "text-center mb-12" },
                    React.createElement("div", { className: "flex justify-center mb-6" },
                        React.createElement(Shield, { className: "h-16 w-16 text-blue-600" })),
                    React.createElement("h1", { className: "text-4xl font-bold text-gray-900 mb-4" }, "Privacy Policy"),
                    React.createElement("p", { className: "text-lg text-gray-600" },
                        "Last updated: ",
                        new Date().toLocaleDateString())),
                React.createElement("div", { className: "mb-8" },
                    React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "At MediBlog, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website and use our services.")),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(Eye, { className: "h-6 w-6 text-blue-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "Information We Collect")),
                    React.createElement("div", { className: "space-y-4" },
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Personal Information"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "Name and email address when you create an account"),
                                React.createElement("li", null, "Professional credentials and medical specialization"),
                                React.createElement("li", null, "Contact information when you reach out to us"),
                                React.createElement("li", null, "Content you create and publish on our platform"))),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Usage Information"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "Pages you visit and time spent on our site"),
                                React.createElement("li", null, "Search queries and content interactions"),
                                React.createElement("li", null, "Device information and browser type"),
                                React.createElement("li", null, "IP address and general location data"))))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(FileText, { className: "h-6 w-6 text-green-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "How We Use Your Information")),
                    React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-2" },
                        React.createElement("li", null, "To provide and maintain our medical content platform"),
                        React.createElement("li", null, "To authenticate users and manage accounts"),
                        React.createElement("li", null, "To enable content creation and collaboration"),
                        React.createElement("li", null, "To improve our services and user experience"),
                        React.createElement("li", null, "To communicate important updates and notifications"),
                        React.createElement("li", null, "To ensure content quality and medical accuracy"),
                        React.createElement("li", null, "To comply with legal obligations and prevent misuse"))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(Users, { className: "h-6 w-6 text-purple-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "Information Sharing")),
                    React.createElement("div", { className: "bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4" },
                        React.createElement("div", { className: "flex items-start" },
                            React.createElement(AlertCircle, { className: "h-5 w-5 text-blue-600 mr-2 mt-0.5 flex-shrink-0" }),
                            React.createElement("p", { className: "text-blue-800 text-sm" },
                                React.createElement("strong", null, "We do not sell, trade, or rent your personal information to third parties.")))),
                    React.createElement("p", { className: "text-gray-700 mb-4" }, "We may share your information only in the following circumstances:"),
                    React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-2" },
                        React.createElement("li", null,
                            React.createElement("strong", null, "With your consent:"),
                            " When you explicitly agree to share information"),
                        React.createElement("li", null,
                            React.createElement("strong", null, "Service providers:"),
                            " Trusted partners who help us operate our platform"),
                        React.createElement("li", null,
                            React.createElement("strong", null, "Legal requirements:"),
                            " When required by law or to protect our rights"),
                        React.createElement("li", null,
                            React.createElement("strong", null, "Medical verification:"),
                            " To verify credentials with medical boards (with consent)"),
                        React.createElement("li", null,
                            React.createElement("strong", null, "Published content:"),
                            " Articles and content you choose to publish publicly"))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(Lock, { className: "h-6 w-6 text-red-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "Data Security")),
                    React.createElement("p", { className: "text-gray-700 mb-4" }, "We implement appropriate technical and organizational security measures to protect your personal information:"),
                    React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-2" },
                        React.createElement("li", null, "Encryption of data in transit and at rest"),
                        React.createElement("li", null, "Regular security audits and vulnerability assessments"),
                        React.createElement("li", null, "Access controls and authentication requirements"),
                        React.createElement("li", null, "Secure hosting infrastructure with backup systems"),
                        React.createElement("li", null, "Staff training on data protection and privacy"))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Your Rights and Choices"),
                    React.createElement("div", { className: "grid md:grid-cols-2 gap-6" },
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Access and Control"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1 text-sm" },
                                React.createElement("li", null, "View and update your account information"),
                                React.createElement("li", null, "Download your data"),
                                React.createElement("li", null, "Delete your account"),
                                React.createElement("li", null, "Opt out of communications"))),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Privacy Controls"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1 text-sm" },
                                React.createElement("li", null, "Control profile visibility"),
                                React.createElement("li", null, "Manage content permissions"),
                                React.createElement("li", null, "Set communication preferences"),
                                React.createElement("li", null, "Request data correction"))))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Cookies and Tracking"),
                    React.createElement("p", { className: "text-gray-700 mb-4" }, "We use cookies and similar technologies to enhance your experience:"),
                    React.createElement("div", { className: "bg-gray-50 rounded-lg p-4" },
                        React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1 text-sm" },
                            React.createElement("li", null,
                                React.createElement("strong", null, "Essential cookies:"),
                                " Required for basic site functionality"),
                            React.createElement("li", null,
                                React.createElement("strong", null, "Analytics cookies:"),
                                " Help us understand how you use our site"),
                            React.createElement("li", null,
                                React.createElement("strong", null, "Preference cookies:"),
                                " Remember your settings and preferences"),
                            React.createElement("li", null,
                                React.createElement("strong", null, "Security cookies:"),
                                " Protect against fraud and unauthorized access")))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Children's Privacy"),
                    React.createElement("p", { className: "text-gray-700" }, "Our services are not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us immediately.")),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Changes to This Policy"),
                    React.createElement("p", { className: "text-gray-700" }, "We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the \"Last updated\" date. We encourage you to review this Privacy Policy periodically for any changes.")),
                React.createElement("section", { className: "bg-blue-50 border border-blue-200 rounded-lg p-6" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Contact Us"),
                    React.createElement("p", { className: "text-gray-700 mb-4" }, "If you have any questions about this Privacy Policy or our data practices, please contact us:"),
                    React.createElement("div", { className: "space-y-2 text-gray-700" },
                        React.createElement("p", null,
                            React.createElement("strong", null, "Email:"),
                            " privacy@mediblog.com"),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Phone:"),
                            " +1 (555) MEDI-BLOG"),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Address:"),
                            " 123 Medical Center Drive, Healthcare District, New York, NY 10001")))))));
}
