import React from 'react';
import { FileText, AlertTriangle, Shield, Users, Gavel, CheckCircle } from 'lucide-react';
export function TermsConditions() {
    return (React.createElement("div", { className: "min-h-screen bg-gray-50 py-12" },
        React.createElement("div", { className: "max-w-4xl mx-auto px-4 sm:px-6 lg:px-8" },
            React.createElement("div", { className: "bg-white rounded-xl shadow-lg p-8" },
                React.createElement("div", { className: "text-center mb-12" },
                    React.createElement("div", { className: "flex justify-center mb-6" },
                        React.createElement(FileText, { className: "h-16 w-16 text-blue-600" })),
                    React.createElement("h1", { className: "text-4xl font-bold text-gray-900 mb-4" }, "Terms and Conditions"),
                    React.createElement("p", { className: "text-lg text-gray-600" },
                        "Last updated: ",
                        new Date().toLocaleDateString())),
                React.createElement("div", { className: "mb-8" },
                    React.createElement("p", { className: "text-gray-700 leading-relaxed" }, "Welcome to MediBlog. These Terms and Conditions (\"Terms\") govern your use of our website and services. By accessing or using MediBlog, you agree to be bound by these Terms. If you disagree with any part of these terms, then you may not access the service.")),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "bg-red-50 border border-red-200 rounded-lg p-6" },
                        React.createElement("div", { className: "flex items-start" },
                            React.createElement(AlertTriangle, { className: "h-6 w-6 text-red-600 mr-3 mt-1 flex-shrink-0" }),
                            React.createElement("div", null,
                                React.createElement("h2", { className: "text-xl font-bold text-red-900 mb-2" }, "Important Medical Disclaimer"),
                                React.createElement("p", { className: "text-red-800 text-sm leading-relaxed" }, "The information provided on MediBlog is for educational and informational purposes only. It is not intended as a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition."))))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(CheckCircle, { className: "h-6 w-6 text-green-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "Acceptance of Terms")),
                    React.createElement("p", { className: "text-gray-700 mb-4" }, "By accessing and using MediBlog, you accept and agree to be bound by the terms and provision of this agreement."),
                    React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-2" },
                        React.createElement("li", null, "You must be at least 18 years old to use our services"),
                        React.createElement("li", null, "You must provide accurate and complete information when creating an account"),
                        React.createElement("li", null, "You are responsible for maintaining the confidentiality of your account"),
                        React.createElement("li", null, "You agree to notify us immediately of any unauthorized use of your account"))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(Users, { className: "h-6 w-6 text-blue-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "User Accounts and Responsibilities")),
                    React.createElement("div", { className: "space-y-4" },
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Account Registration"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "Provide accurate, current, and complete information"),
                                React.createElement("li", null, "Maintain and update your information to keep it accurate"),
                                React.createElement("li", null, "Medical professionals must provide valid credentials"),
                                React.createElement("li", null, "One account per person or organization"))),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Account Security"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "You are responsible for safeguarding your password"),
                                React.createElement("li", null, "You must not share your account with others"),
                                React.createElement("li", null, "Notify us immediately of any security breaches"),
                                React.createElement("li", null, "We reserve the right to suspend accounts for security reasons"))))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(FileText, { className: "h-6 w-6 text-purple-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "Content Guidelines")),
                    React.createElement("div", { className: "space-y-4" },
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Content Standards"),
                            React.createElement("p", { className: "text-gray-700 mb-2" }, "All content published on MediBlog must:"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "Be medically accurate and evidence-based"),
                                React.createElement("li", null, "Be written by qualified healthcare professionals"),
                                React.createElement("li", null, "Include proper citations and references"),
                                React.createElement("li", null, "Comply with medical ethics and professional standards"),
                                React.createElement("li", null, "Be original or properly attributed"))),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Prohibited Content"),
                            React.createElement("p", { className: "text-gray-700 mb-2" }, "The following content is strictly prohibited:"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "Misleading or false medical information"),
                                React.createElement("li", null, "Promotion of unproven treatments or cures"),
                                React.createElement("li", null, "Personal medical advice or diagnosis"),
                                React.createElement("li", null, "Copyrighted material without permission"),
                                React.createElement("li", null, "Discriminatory or offensive content"),
                                React.createElement("li", null, "Commercial advertisements disguised as content"))))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(Shield, { className: "h-6 w-6 text-green-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "Intellectual Property Rights")),
                    React.createElement("div", { className: "space-y-4" },
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Your Content"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "You retain ownership of content you create and publish"),
                                React.createElement("li", null, "You grant us a license to display, distribute, and promote your content"),
                                React.createElement("li", null, "You warrant that you have the right to publish the content"),
                                React.createElement("li", null, "You are responsible for any copyright infringement claims"))),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "Our Content"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "MediBlog platform, design, and features are our property"),
                                React.createElement("li", null, "You may not copy, modify, or distribute our platform"),
                                React.createElement("li", null, "Our trademarks and logos are protected"),
                                React.createElement("li", null, "User-generated content remains the property of respective authors"))))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Privacy and Data Protection"),
                    React.createElement("p", { className: "text-gray-700 mb-4" }, "Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information. By using our services, you also agree to our Privacy Policy."),
                    React.createElement("div", { className: "bg-blue-50 border border-blue-200 rounded-lg p-4" },
                        React.createElement("p", { className: "text-blue-800 text-sm" },
                            React.createElement("strong", null, "Note:"),
                            " We comply with HIPAA regulations and maintain strict confidentiality standards for all medical information shared on our platform."))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("div", { className: "flex items-center mb-4" },
                        React.createElement(Gavel, { className: "h-6 w-6 text-red-600 mr-3" }),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-900" }, "Limitation of Liability")),
                    React.createElement("div", { className: "bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-4" },
                        React.createElement("p", { className: "text-yellow-800 text-sm" },
                            React.createElement("strong", null, "Important:"),
                            " MediBlog provides information for educational purposes only. We are not liable for any medical decisions made based on information from our platform.")),
                    React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-2" },
                        React.createElement("li", null, "We provide the platform \"as is\" without warranties of any kind"),
                        React.createElement("li", null, "We are not responsible for the accuracy of user-generated content"),
                        React.createElement("li", null, "We are not liable for any damages arising from use of our services"),
                        React.createElement("li", null, "Our liability is limited to the maximum extent permitted by law"),
                        React.createElement("li", null, "Users assume full responsibility for their use of the information provided"))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Termination"),
                    React.createElement("div", { className: "space-y-4" },
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "By You"),
                            React.createElement("p", { className: "text-gray-700" }, "You may terminate your account at any time by contacting us or using the account deletion feature.")),
                        React.createElement("div", null,
                            React.createElement("h3", { className: "text-lg font-semibold text-gray-900 mb-2" }, "By Us"),
                            React.createElement("p", { className: "text-gray-700 mb-2" }, "We may terminate or suspend your account if you:"),
                            React.createElement("ul", { className: "list-disc list-inside text-gray-700 space-y-1" },
                                React.createElement("li", null, "Violate these Terms and Conditions"),
                                React.createElement("li", null, "Publish misleading or harmful medical information"),
                                React.createElement("li", null, "Engage in fraudulent or illegal activities"),
                                React.createElement("li", null, "Violate intellectual property rights"))))),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Governing Law"),
                    React.createElement("p", { className: "text-gray-700" }, "These Terms shall be interpreted and governed by the laws of the State of New York, United States, without regard to its conflict of law provisions. Any disputes arising from these Terms will be resolved in the courts of New York.")),
                React.createElement("section", { className: "mb-8" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Changes to Terms"),
                    React.createElement("p", { className: "text-gray-700" }, "We reserve the right to modify these Terms at any time. We will notify users of any material changes via email or through our platform. Your continued use of MediBlog after such modifications constitutes acceptance of the updated Terms.")),
                React.createElement("section", { className: "bg-blue-50 border border-blue-200 rounded-lg p-6" },
                    React.createElement("h2", { className: "text-2xl font-bold text-gray-900 mb-4" }, "Contact Us"),
                    React.createElement("p", { className: "text-gray-700 mb-4" }, "If you have any questions about these Terms and Conditions, please contact us:"),
                    React.createElement("div", { className: "space-y-2 text-gray-700" },
                        React.createElement("p", null,
                            React.createElement("strong", null, "Email:"),
                            " legal@mediblog.com"),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Phone:"),
                            " +1 (555) MEDI-BLOG"),
                        React.createElement("p", null,
                            React.createElement("strong", null, "Address:"),
                            " 123 Medical Center Drive, Healthcare District, New York, NY 10001")))))));
}
