import React from 'react';
import { Link } from 'react-router-dom';
import { Stethoscope, Mail, Phone, MapPin, Facebook, Twitter, Linkedin, Instagram } from 'lucide-react';
export function Footer() {
    const scrollToTop = () => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };
    return (React.createElement("footer", { className: "bg-gray-900 text-white" },
        React.createElement("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12" },
            React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8" },
                React.createElement("div", { className: "lg:col-span-1" },
                    React.createElement("div", { className: "flex items-center space-x-3 mb-4" },
                        React.createElement(Stethoscope, { className: "h-8 w-8 text-blue-400" }),
                        React.createElement("span", { className: "text-2xl font-bold" }, "MediBlog")),
                    React.createElement("p", { className: "text-gray-300 mb-6 leading-relaxed" }, "Your trusted source for medical knowledge, health insights, and professional healthcare content. Empowering healthcare professionals and patients with accurate, evidence-based information."),
                    React.createElement("div", { className: "flex space-x-4" },
                        React.createElement("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors" },
                            React.createElement(Facebook, { size: 20 })),
                        React.createElement("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors" },
                            React.createElement(Twitter, { size: 20 })),
                        React.createElement("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors" },
                            React.createElement(Linkedin, { size: 20 })),
                        React.createElement("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors" },
                            React.createElement(Instagram, { size: 20 })))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-lg font-semibold mb-4" }, "Quick Links"),
                    React.createElement("ul", { className: "space-y-3" },
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/", onClick: scrollToTop, className: "text-gray-300 hover:text-white transition-colors" }, "Home")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/about", onClick: scrollToTop, className: "text-gray-300 hover:text-white transition-colors" }, "About Us")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/contact", onClick: scrollToTop, className: "text-gray-300 hover:text-white transition-colors" }, "Contact")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/get-access", onClick: scrollToTop, className: "text-gray-300 hover:text-white transition-colors" }, "Get Access")))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-lg font-semibold mb-4" }, "Medical Specialties"),
                    React.createElement("ul", { className: "space-y-3 text-gray-300" },
                        React.createElement("li", null, "Cardiology"),
                        React.createElement("li", null, "Pediatrics"),
                        React.createElement("li", null, "Neurology"),
                        React.createElement("li", null, "Oncology"),
                        React.createElement("li", null, "Dermatology"),
                        React.createElement("li", null, "Orthopedics"))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-lg font-semibold mb-4" }, "Contact Info"),
                    React.createElement("div", { className: "space-y-3" },
                        React.createElement("div", { className: "flex items-start space-x-3" },
                            React.createElement(MapPin, { className: "h-5 w-5 text-blue-400 mt-0.5 flex-shrink-0" }),
                            React.createElement("div", { className: "text-gray-300" },
                                React.createElement("p", null, "123 Medical Center Drive"),
                                React.createElement("p", null, "Healthcare District"),
                                React.createElement("p", null, "New York, NY 10001"))),
                        React.createElement("div", { className: "flex items-center space-x-3" },
                            React.createElement(Phone, { className: "h-5 w-5 text-blue-400 flex-shrink-0" }),
                            React.createElement("a", { href: "tel:+1-555-MEDIBLOG", className: "text-gray-300 hover:text-white transition-colors" }, "+1 (555) MEDI-BLOG")),
                        React.createElement("div", { className: "flex items-center space-x-3" },
                            React.createElement(Mail, { className: "h-5 w-5 text-blue-400 flex-shrink-0" }),
                            React.createElement("a", { href: "mailto:contact@mediblog.com", className: "text-gray-300 hover:text-white transition-colors" }, "contact@mediblog.com"))))),
            React.createElement("div", { className: "border-t border-gray-800 mt-12 pt-8" },
                React.createElement("div", { className: "flex flex-col md:flex-row justify-between items-center" },
                    React.createElement("div", { className: "text-gray-400 text-sm mb-4 md:mb-0" },
                        "\u00A9 ",
                        new Date().getFullYear(),
                        " MediBlog. All rights reserved."),
                    React.createElement("div", { className: "flex flex-wrap justify-center md:justify-end space-x-6 text-sm" },
                        React.createElement(Link, { to: "/privacy-policy", onClick: scrollToTop, className: "text-gray-400 hover:text-white transition-colors" }, "Privacy Policy"),
                        React.createElement(Link, { to: "/terms-conditions", onClick: scrollToTop, className: "text-gray-400 hover:text-white transition-colors" }, "Terms & Conditions"),
                        React.createElement("a", { href: "#", className: "text-gray-400 hover:text-white transition-colors" }, "Cookie Policy"),
                        React.createElement("a", { href: "#", className: "text-gray-400 hover:text-white transition-colors" }, "Sitemap"))),
                React.createElement("div", { className: "mt-6 p-4 bg-gray-800 rounded-lg" },
                    React.createElement("p", { className: "text-gray-400 text-xs leading-relaxed" },
                        React.createElement("strong", null, "Medical Disclaimer:"),
                        " The information provided on MediBlog is for educational and informational purposes only. It is not intended as a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition."))))));
}
